export type RestaurantCity = "dammam" | "saihat" | "qatif";

export type SeedRestaurant = {
  name: string;
  category: string;
  city: RestaurantCity;
  address: string;
  notes: string;
  priceRange: "$" | "$$" | "$$$";
  /** Cuisine-matched Unsplash photo (illustrative; not a claimed venue exterior). */
  imageUrl: string;
};

const img = {
  shrimp:
    "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80",
  fish: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&q=80",
  lobster:
    "https://images.unsplash.com/photo-1559847844-5315695dadae?w=800&q=80",
  sushi: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&q=80",
  kabsa:
    "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&q=80",
  rice: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=800&q=80",
  shawarma:
    "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800&q=80",
  grill: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f3?w=800&q=80",
  mezze:
    "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=800&q=80",
  steak: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800&q=80",
  burger:
    "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
  pizza: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80",
  chicken:
    "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=800&q=80",
  indian:
    "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80",
  chinese:
    "https://images.unsplash.com/photo-1525755662778-989d0524087e?w=800&q=80",
  italian:
    "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&q=80",
  sandwich:
    "https://images.unsplash.com/photo-1553909489-cd47e0907980?w=800&q=80",
  feast: "https://images.unsplash.com/photo-1555939594-58ed7cd077c0?w=800&q=80",
};

/** High-quality Eastern Province picks for Dammam / Saihat / Qatif (~40). */
export const EASTERN_PROVINCE_RESTAURANTS: SeedRestaurant[] = [
  // —— Dammam (22) ——
  {
    name: "Shrimp Shack",
    category: "Seafood",
    city: "dammam",
    address: "King Fahd Rd, Al Faisaliyah, Dammam",
    notes: "Crowd favorite for grilled shrimp and casual seafood.",
    priceRange: "$$",
    imageUrl: img.shrimp,
  },
  {
    name: "Bait Al Robyan",
    category: "Seafood",
    city: "dammam",
    address: "Al Hamra / Khaleej Rd, Dammam",
    notes: "Family seafood institution — shrimp and hammour plates.",
    priceRange: "$$",
    imageUrl: img.fish,
  },
  {
    name: "Darin Seafood",
    category: "Seafood",
    city: "dammam",
    address: "Al Hamra, Dammam",
    notes: "Reliable mid-range seafood for the whole crew.",
    priceRange: "$$",
    imageUrl: img.lobster,
  },
  {
    name: "Horyat Al Sharqia",
    category: "Seafood",
    city: "dammam",
    address: "Dammam",
    notes: "Fresh Gulf seafood, popular with locals.",
    priceRange: "$$",
    imageUrl: img.fish,
  },
  {
    name: "Aish O Samach (Dammam)",
    category: "Seafood",
    city: "dammam",
    address: "Al Quds St, Majidyah, Dammam",
    notes: "Seafood, sushi, and grilled fish under banana leaf.",
    priceRange: "$$$",
    imageUrl: img.sushi,
  },
  {
    name: "Oceana",
    category: "Seafood",
    city: "dammam",
    address: "Corniche / Al Shati, Dammam",
    notes: "Waterfront-leaning seafood night.",
    priceRange: "$$$",
    imageUrl: img.lobster,
  },
  {
    name: "Heritage Village",
    category: "Saudi",
    city: "dammam",
    address: "Corniche, Dammam",
    notes: "Kabsa and mandi in a heritage setting.",
    priceRange: "$$",
    imageUrl: img.kabsa,
  },
  {
    name: "Al-Romansiah",
    category: "Saudi",
    city: "dammam",
    address: "Ar Rakah, Dammam",
    notes: "Go-to for consistent Saudi rice dishes.",
    priceRange: "$$",
    imageUrl: img.rice,
  },
  {
    name: "Al Kabsa Al Damamiah",
    category: "Saudi",
    city: "dammam",
    address: "Ar Rakah, Dammam",
    notes: "Local kabsa classic.",
    priceRange: "$",
    imageUrl: img.kabsa,
  },
  {
    name: "Mama Noura",
    category: "Saudi",
    city: "dammam",
    address: "Multiple branches, Dammam",
    notes: "Saudi fast-casual: sandwiches, breakfast, grilled meats.",
    priceRange: "$",
    imageUrl: img.shawarma,
  },
  {
    name: "Al Baik (Dammam)",
    category: "Other",
    city: "dammam",
    address: "Dammam branches",
    notes: "Iconic Saudi fried chicken — expect a queue.",
    priceRange: "$",
    imageUrl: img.chicken,
  },
  {
    name: "Najd Village",
    category: "Saudi",
    city: "dammam",
    address: "Dammam",
    notes: "Traditional Najdi flavors for a crew dinner.",
    priceRange: "$$",
    imageUrl: img.feast,
  },
  {
    name: "Mijana",
    category: "Lebanese",
    city: "dammam",
    address: "Dammam",
    notes: "Consistent Lebanese mezze and grills.",
    priceRange: "$$",
    imageUrl: img.mezze,
  },
  {
    name: "Beit Misk",
    category: "Lebanese",
    city: "dammam",
    address: "Dammam",
    notes: "Lebanese comfort food and grills.",
    priceRange: "$$",
    imageUrl: img.grill,
  },
  {
    name: "Abu Nawas",
    category: "Lebanese",
    city: "dammam",
    address: "Dammam",
    notes: "Levantine staples for sharing plates.",
    priceRange: "$$",
    imageUrl: img.mezze,
  },
  {
    name: "Shaw Shawarma",
    category: "Sandwiches",
    city: "dammam",
    address: "King Fahd Rd area, Dammam",
    notes: "Late-night shawarma after the movie.",
    priceRange: "$",
    imageUrl: img.shawarma,
  },
  {
    name: "Shajarat Al-Durr",
    category: "Kebab",
    city: "dammam",
    address: "Dammam",
    notes: "Grilled meats and barbecue plates.",
    priceRange: "$$",
    imageUrl: img.grill,
  },
  {
    name: "Butcher Shop & Grill",
    category: "Steakhouse",
    city: "dammam",
    address: "Mall of Dhahran area, Dammam",
    notes: "Steaks when the crew wants something heavier.",
    priceRange: "$$$",
    imageUrl: img.steak,
  },
  {
    name: "Steak House",
    category: "Steakhouse",
    city: "dammam",
    address: "Mall of Dhahran / Dammam",
    notes: "Classic steakhouse night.",
    priceRange: "$$$",
    imageUrl: img.steak,
  },
  {
    name: "Brasil Churrascaria",
    category: "Steakhouse",
    city: "dammam",
    address: "Dammam",
    notes: "Brazilian-style grill for big appetites.",
    priceRange: "$$$",
    imageUrl: img.grill,
  },
  {
    name: "Fuddruckers",
    category: "Burgers",
    city: "dammam",
    address: "Dammam",
    notes: "Build-your-own burger night.",
    priceRange: "$$",
    imageUrl: img.burger,
  },
  {
    name: "Maharaja",
    category: "Indian",
    city: "dammam",
    address: "Dammam / Dhahran corridor",
    notes: "Indian and Mughlai when the crew wants spice.",
    priceRange: "$$$",
    imageUrl: img.indian,
  },
  // —— Qatif (10) ——
  {
    name: "Samakati (Corniche)",
    category: "Seafood",
    city: "qatif",
    address: "Gulf Rd, Fish Island, Qatif Corniche",
    notes: "Flagship Samakati — nautical seafood since 2006.",
    priceRange: "$$",
    imageUrl: img.fish,
  },
  {
    name: "Samakati (Badr Street)",
    category: "Seafood",
    city: "qatif",
    address: "Badr St, opposite Old Fish Market, Qatif",
    notes: "Second Samakati branch near the fish market.",
    priceRange: "$$",
    imageUrl: img.shrimp,
  },
  {
    name: "Aish O Samach (Qatif)",
    category: "Seafood",
    city: "qatif",
    address: "Entrance of Qatif",
    notes: "Fine seafood and sushi at the Qatif entrance.",
    priceRange: "$$$",
    imageUrl: img.sushi,
  },
  {
    name: "Qatif Fish Market Grills",
    category: "Seafood",
    city: "qatif",
    address: "Near Old Fish Market, Qatif",
    notes: "Buy fresh and grill nearby — classic Qatif move.",
    priceRange: "$",
    imageUrl: img.fish,
  },
  {
    name: "Al Sayyad",
    category: "Seafood",
    city: "qatif",
    address: "Qatif",
    notes: "Local seafood house for hammour and shrimp.",
    priceRange: "$$",
    imageUrl: img.lobster,
  },
  {
    name: "Bayt Al Samak",
    category: "Seafood",
    city: "qatif",
    address: "Qatif",
    notes: "House of fish — family tables and Gulf classics.",
    priceRange: "$$",
    imageUrl: img.fish,
  },
  {
    name: "Qatif Shawarma Corner",
    category: "Sandwiches",
    city: "qatif",
    address: "Central Qatif",
    notes: "Quick shawarma stop between Saihat and Dammam.",
    priceRange: "$",
    imageUrl: img.shawarma,
  },
  {
    name: "Al Rawda Grills (Qatif)",
    category: "Kebab",
    city: "qatif",
    address: "Qatif",
    notes: "Mixed grill platters for a hungry crew.",
    priceRange: "$$",
    imageUrl: img.grill,
  },
  {
    name: "Levant House Qatif",
    category: "Lebanese",
    city: "qatif",
    address: "Qatif",
    notes: "Mezze and charcoal grills.",
    priceRange: "$$",
    imageUrl: img.mezze,
  },
  {
    name: "Mandi Express Qatif",
    category: "Yemeni",
    city: "qatif",
    address: "Qatif",
    notes: "Yemeni mandi and haneeth for rice-night.",
    priceRange: "$",
    imageUrl: img.rice,
  },
  // —— Saihat (8) ——
  {
    name: "Asiakh Grills",
    category: "Kebab",
    city: "saihat",
    address: "Saihat",
    notes: "Accessible kebabs and grills — Saihat staple.",
    priceRange: "$$",
    imageUrl: img.grill,
  },
  {
    name: "Madad Restaurant",
    category: "Saudi",
    city: "saihat",
    address: "Saihat",
    notes: "Regional Saudi and Middle Eastern dining.",
    priceRange: "$$",
    imageUrl: img.kabsa,
  },
  {
    name: "Saihat Seafood House",
    category: "Seafood",
    city: "saihat",
    address: "Saihat",
    notes: "Coastal seafood between Qatif and Dammam.",
    priceRange: "$$",
    imageUrl: img.shrimp,
  },
  {
    name: "Corniche Saihat Fish",
    category: "Seafood",
    city: "saihat",
    address: "Saihat Corniche area",
    notes: "Fresh catch and simple grilled fish.",
    priceRange: "$$",
    imageUrl: img.fish,
  },
  {
    name: "Saihat Shawarma",
    category: "Sandwiches",
    city: "saihat",
    address: "Central Saihat",
    notes: "Quick post-movie sandwiches.",
    priceRange: "$",
    imageUrl: img.sandwich,
  },
  {
    name: "Al Madina Pizza Saihat",
    category: "Pizza",
    city: "saihat",
    address: "Saihat",
    notes: "Local pizza when the crew wants easy sharing.",
    priceRange: "$",
    imageUrl: img.pizza,
  },
  {
    name: "Burger Joint Saihat",
    category: "Burgers",
    city: "saihat",
    address: "Saihat",
    notes: "Casual burgers for a low-key night.",
    priceRange: "$",
    imageUrl: img.burger,
  },
  {
    name: "Yemeni Mandi Saihat",
    category: "Yemeni",
    city: "saihat",
    address: "Saihat",
    notes: "Mandi and rice platters for groups.",
    priceRange: "$",
    imageUrl: img.rice,
  },
];
