const TMDB = "https://image.tmdb.org/t/p/w342";
const BACKDROP = "https://image.tmdb.org/t/p/w1280";

export type SeedMovie = {
  tmdbId: number;
  title: string;
  posterPath: string;
  backdropPath?: string;
  overview: string;
  genres: string[];
  runtime?: number;
  releaseYear: number;
  imdbRating?: number;
};

export type SeedCollection = {
  name: string;
  description: string;
  movies: SeedMovie[];
};

function movie(
  tmdbId: number,
  title: string,
  posterPath: string,
  releaseYear: number,
  overview: string,
  genres: string[],
  extras?: Partial<
    Pick<SeedMovie, "runtime" | "imdbRating" | "backdropPath">
  >,
): SeedMovie {
  return {
    tmdbId,
    title,
    posterPath,
    releaseYear,
    overview,
    genres,
    ...extras,
  };
}

/** Curated themed lists for the owner account. Idempotent by collection name. */
export const CURATED_COLLECTIONS: SeedCollection[] = [
  {
    name: "Opening Night Classics",
    description:
      "Films that still feel like an event — dim the lights and tell everyone to put their phones away.",
    movies: [
      movie(
        238,
        "The Godfather",
        "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
        1972,
        "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
        ["Drama", "Crime"],
        { runtime: 175, imdbRating: 8.7 },
      ),
      movie(
        289,
        "Casablanca",
        "/lGCEKlJo2CnWydQj7aamY7s1S7Q.jpg",
        1942,
        "A cynical expatriate café owner is forced to choose between love and virtue in wartime Morocco.",
        ["Drama", "Romance"],
        { runtime: 102, imdbRating: 8.5 },
      ),
      movie(
        62,
        "2001: A Space Odyssey",
        "/ve72VxNqjGM69Uky4WTo2bK6rfq.jpg",
        1968,
        "Humanity finds a mysterious object beneath the lunar surface and sets off with HAL 9000.",
        ["Science Fiction", "Mystery", "Adventure"],
        { runtime: 149, imdbRating: 8.0 },
      ),
      movie(
        346,
        "Seven Samurai",
        "/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg",
        1954,
        "Farmers hire seven warriors to defend their village — the blueprint for every team-up since.",
        ["Action", "Drama"],
        { runtime: 207, imdbRating: 8.6 },
      ),
      movie(
        15,
        "Citizen Kane",
        "/sav0jxhqiH0bPr2vZFU0Kjt2nZL.jpg",
        1941,
        "A reporter digs into a media tycoon's last word and finds a life that refuses a simple answer.",
        ["Mystery", "Drama"],
        { runtime: 119, imdbRating: 8.0 },
      ),
      movie(
        278,
        "The Shawshank Redemption",
        "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
        1994,
        "Two imprisoned men bond over years, finding solace and eventual redemption through acts of common decency.",
        ["Drama", "Crime"],
        { runtime: 142, imdbRating: 8.7 },
      ),
      movie(
        680,
        "Pulp Fiction",
        "/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
        1994,
        "Intersecting stories of L.A. criminals, a boxer, and a briefcase that should never be opened.",
        ["Thriller", "Crime"],
        { runtime: 154, imdbRating: 8.5 },
      ),
      movie(
        769,
        "GoodFellas",
        "/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg",
        1990,
        "Henry Hill grows up inside the mob — and learns how quickly the lifestyle eats its own.",
        ["Drama", "Crime"],
        { runtime: 145, imdbRating: 8.5 },
      ),
    ],
  },
  {
    name: "Comfort Rewatches",
    description:
      "Soft landings for tired nights. You already know the beats — that's the point.",
    movies: [
      movie(
        129,
        "Spirited Away",
        "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
        2001,
        "A girl wanders into a spirit bathhouse and has to earn her way back to the human world.",
        ["Animation", "Family", "Fantasy"],
        { runtime: 125, imdbRating: 8.5 },
      ),
      movie(
        120467,
        "The Grand Budapest Hotel",
        "/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
        2014,
        "A legendary concierge and his lobby boy scramble through a continent of pastel chaos.",
        ["Comedy", "Drama"],
        { runtime: 99, imdbRating: 8.1 },
      ),
      movie(
        194,
        "Amélie",
        "/nSxDa3M9aMvGVLoItzWTepQ5h5d.jpg",
        2001,
        "A shy waitress in Montmartre sets out to quietly improve the lives of strangers — and maybe her own.",
        ["Comedy", "Romance"],
        { runtime: 122, imdbRating: 8.3 },
      ),
      movie(
        76,
        "Before Sunrise",
        "/kf1Jb1c2JAOqjuzA3H4oDM263uB.jpg",
        1995,
        "Two strangers spend one night walking Vienna and talking like the morning will never come.",
        ["Drama", "Romance"],
        { runtime: 101, imdbRating: 8.0 },
      ),
      movie(
        346648,
        "Paddington 2",
        "/1OJ9vkD5xPt3skC6KguyXAgagRZ.jpg",
        2017,
        "A bear with excellent manners tries to fix a wrong — peak kindness as cinema.",
        ["Adventure", "Comedy", "Family"],
        { runtime: 103, imdbRating: 7.8 },
      ),
      movie(
        8392,
        "My Neighbor Totoro",
        "/rtGDOeG9LzoerkDGZF9dnVeLppL.jpg",
        1988,
        "Two sisters discover forest spirits while waiting for their mother to recover.",
        ["Fantasy", "Animation", "Family"],
        { runtime: 86, imdbRating: 8.1 },
      ),
      movie(
        12,
        "Finding Nemo",
        "/5lc6nQc0VhWFYFbNv016xze8Jvy.jpg",
        2003,
        "A clownfish crosses the ocean to find his son — and learns to let go just enough.",
        ["Animation", "Family"],
        { runtime: 100, imdbRating: 7.8 },
      ),
      movie(
        324857,
        "Spider-Man: Into the Spider-Verse",
        "/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
        2018,
        "Miles Morales swings into a multiverse of Spider-People — joyful, stylish, and endlessly rewatchable.",
        ["Animation", "Action", "Adventure"],
        { runtime: 117, imdbRating: 8.4 },
      ),
    ],
  },
  {
    name: "Mindbenders",
    description:
      "Puzzle boxes, timeline traps, and endings that demand a second watch before anyone opens their mouth.",
    movies: [
      movie(
        27205,
        "Inception",
        "/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg",
        2010,
        "A thief who steals secrets through dreams is offered a chance at redemption — if he can plant an idea.",
        ["Action", "Science Fiction", "Adventure"],
        { runtime: 148, imdbRating: 8.4 },
      ),
      movie(
        1124,
        "The Prestige",
        "/Ag2B2KHKQPukjH7WutmgnnSNurZ.jpg",
        2006,
        "Rival magicians escalate a feud until the trick costs more than either can afford.",
        ["Drama", "Mystery", "Science Fiction"],
        { runtime: 130, imdbRating: 8.5 },
      ),
      movie(
        329865,
        "Arrival",
        "/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
        2016,
        "A linguist races to understand an alien language that might rewrite how we experience time.",
        ["Drama", "Science Fiction", "Mystery"],
        { runtime: 116, imdbRating: 7.9 },
      ),
      movie(
        220289,
        "Coherence",
        "/ezUtb9m5DeLwL2gxi4gktzNCvQv.jpg",
        2014,
        "A comet night dinner party slips into overlapping realities — low budget, high dread.",
        ["Science Fiction", "Thriller"],
        { runtime: 89, imdbRating: 7.2 },
      ),
      movie(
        14337,
        "Primer",
        "/xEoq2WmDzpzxhkHEsmOYOg6BPg6.jpg",
        2004,
        "Two engineers invent time travel in a garage and immediately make the worst possible decisions.",
        ["Science Fiction", "Drama", "Thriller"],
        { runtime: 77, imdbRating: 6.8 },
      ),
      movie(
        77,
        "Memento",
        "/nzlv62aC0octS5AklAiWpXLX9Z0.jpg",
        2000,
        "A man with short-term memory loss tattoos clues on himself while hunting his wife's killer.",
        ["Mystery", "Thriller"],
        { runtime: 113, imdbRating: 8.2 },
      ),
      movie(
        11324,
        "Shutter Island",
        "/nrmXQ0zcZUL8jFLrakWc90IR8z9.jpg",
        2010,
        "A U.S. Marshal investigates a missing patient on an island hospital that won't give up its secrets.",
        ["Drama", "Thriller", "Mystery"],
        { runtime: 138, imdbRating: 8.2 },
      ),
      movie(
        550,
        "Fight Club",
        "/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg",
        1999,
        "An insomniac and a soap salesman start an underground fight club that becomes something else entirely.",
        ["Drama"],
        { runtime: 139, imdbRating: 8.4 },
      ),
    ],
  },
  {
    name: "Epic Runtime Challenges",
    description:
      "Commit to the chair. Long-haul nights — stretch break optional, snacks mandatory.",
    movies: [
      movie(
        122,
        "The Lord of the Rings: The Return of the King",
        "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
        2003,
        "The fellowship's war for Middle-earth reaches its final, thunderous chapter.",
        ["Adventure", "Fantasy", "Action"],
        { runtime: 201, imdbRating: 8.5 },
      ),
      movie(
        398978,
        "The Irishman",
        "/mbm8k3GFhXS0ROd9AD1gqYbIFbM.jpg",
        2019,
        "A hitman looks back on a life spent in the orbit of Hoffa and the Bufalinos.",
        ["Crime", "Drama", "History"],
        { runtime: 209, imdbRating: 7.8 },
      ),
      movie(
        947,
        "Lawrence of Arabia",
        "/AiAm0EtDvyGqNpVoieRw4u65vD1.jpg",
        1962,
        "Desert, empire, and a man who becomes a myth faster than he can live with it.",
        ["Adventure", "Drama", "History"],
        { runtime: 228, imdbRating: 8.3 },
      ),
      movie(
        311,
        "Once Upon a Time in America",
        "/i0enkzsL5dPeneWnjl1fCWm6L7k.jpg",
        1984,
        "Decades of friendship and betrayal among Jewish gangsters in New York.",
        ["Crime", "Drama"],
        { runtime: 229, imdbRating: 8.3 },
      ),
      movie(
        424,
        "Schindler's List",
        "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
        1993,
        "A businessman builds a list that becomes a lifeline — devastating and essential.",
        ["Drama", "History", "War"],
        { runtime: 195, imdbRating: 8.9 },
      ),
      movie(
        155,
        "The Dark Knight",
        "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        2008,
        "Batman faces the Joker in a crime epic that still sets the bar for comic-book cinema.",
        ["Drama", "Action", "Crime", "Thriller"],
        { runtime: 152, imdbRating: 8.5 },
      ),
      movie(
        693134,
        "Dune: Part Two",
        "/6izwz7rsy95ARzTR3poZ8H6c5pp.jpg",
        2024,
        "Paul Atreides unites with the Fremen and walks a path of prophecy and revenge on Arrakis.",
        ["Science Fiction", "Adventure"],
        { runtime: 167, imdbRating: 8.1 },
      ),
    ],
  },
  {
    name: "Score First",
    description:
      "Turn it up. These nights live or die on the soundtrack — picture and pulse locked together.",
    movies: [
      movie(
        157336,
        "Interstellar",
        "/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg",
        2014,
        "A crew leaves Earth for a wormhole — Zimmer's organ work does half the storytelling.",
        ["Adventure", "Drama", "Science Fiction"],
        { runtime: 169, imdbRating: 8.6 },
      ),
      movie(
        335984,
        "Blade Runner 2049",
        "/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
        2017,
        "A blade runner digs into a buried secret while Vangelis's ghost haunts a new score.",
        ["Science Fiction", "Drama"],
        { runtime: 164, imdbRating: 8.0 },
      ),
      movie(
        244786,
        "Whiplash",
        "/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
        2014,
        "A jazz drummer and a merciless instructor push each other past the edge of artistry.",
        ["Drama", "Music"],
        { runtime: 107, imdbRating: 8.5 },
      ),
      movie(
        64690,
        "Drive",
        "/602vevIURmpDfzbnv5Ubi6wIkQm.jpg",
        2011,
        "A Hollywood stunt driver moonlights as a getaway man — neon, silence, and a killer synth wave.",
        ["Drama", "Action", "Crime"],
        { runtime: 100, imdbRating: 7.8 },
      ),
      movie(
        438631,
        "Dune",
        "/v1tRXZ4JtD2Iv6fjkPvT4GiwslV.jpg",
        2021,
        "House Atreides arrives on Arrakis; Zimmer's choir and drums shake the sand.",
        ["Science Fiction", "Adventure"],
        { runtime: 155, imdbRating: 8.0 },
      ),
      movie(
        49047,
        "Gravity",
        "/kZ2nZw8D681aphje8NJi8EfbL1U.jpg",
        2013,
        "Two astronauts fight to survive after their shuttle is destroyed — silence and score in space.",
        ["Science Fiction", "Thriller", "Drama"],
        { runtime: 91, imdbRating: 7.2 },
      ),
    ],
  },
  {
    name: "Laugh Until It Hurts",
    description:
      "Proper crew comedies — someone will pause the movie because the room can't breathe.",
    movies: [
      movie(
        4638,
        "Hot Fuzz",
        "/zPib4ukTSdXvHP9pxGkFCe34f3y.jpg",
        2007,
        "An elite London cop is dumped in a sleepy village that is definitely not sleepy.",
        ["Action", "Comedy", "Crime"],
        { runtime: 121, imdbRating: 7.8 },
      ),
      movie(
        115,
        "The Big Lebowski",
        "/3bv6WAp6BSxxYvB5ozKFUYuRA8C.jpg",
        1998,
        "The Dude abides — bowling, mistaken identity, and the chillest crime story ever made.",
        ["Comedy", "Crime"],
        { runtime: 117, imdbRating: 8.1 },
      ),
      movie(
        546554,
        "Knives Out",
        "/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
        2019,
        "A detective circles a dysfunctional rich family after a famous novelist dies upstairs.",
        ["Comedy", "Crime", "Mystery"],
        { runtime: 131, imdbRating: 7.9 },
      ),
      movie(
        246741,
        "What We Do in the Shadows",
        "/a2rD3i3DBMeYbA34rBv6z3B9S3a.jpg",
        2014,
        "Flatmate vampires navigate Wellington nightlife in documentary form. Bloody brilliant.",
        ["Comedy", "Horror"],
        { runtime: 86, imdbRating: 7.6 },
      ),
      movie(
        8363,
        "Superbad",
        "/ek8e8txUyUwd2BNqj6lFEerJfbq.jpg",
        2007,
        "Two best friends chase one legendary party before college pulls them apart.",
        ["Comedy"],
        { runtime: 113, imdbRating: 7.6 },
      ),
      movie(
        508947,
        "Turning Red",
        "/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
        2022,
        "A Toronto teen turns into a giant red panda when she gets too excited — chaos and heart.",
        ["Animation", "Family", "Comedy", "Fantasy"],
        { runtime: 100, imdbRating: 7.3 },
      ),
    ],
  },
  {
    name: "Rainy Night Noirs",
    description:
      "Wet streets, bad deals, and faces lit by neon. Best with storm sounds and strong coffee.",
    movies: [
      movie(
        829,
        "Chinatown",
        "/kZRSP3FmOcq0xnBulqpUQngJUXY.jpg",
        1974,
        "A private eye in 1930s LA follows a simple case into water, power, and moral rot.",
        ["Crime", "Drama", "Mystery"],
        { runtime: 130, imdbRating: 8.1 },
      ),
      movie(
        78,
        "Blade Runner",
        "/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg",
        1982,
        "A burnt-out cop hunts replicants through rain-soaked 2019 Los Angeles.",
        ["Science Fiction", "Drama", "Thriller"],
        { runtime: 118, imdbRating: 8.1 },
      ),
      movie(
        242582,
        "Nightcrawler",
        "/j9HrX8f7GbZQm1BrBiR40uFQZSb.jpg",
        2014,
        "A driven loner turns crime-scene footage into a career — and a manifesto.",
        ["Crime", "Drama", "Thriller"],
        { runtime: 117, imdbRating: 7.8 },
      ),
      movie(
        210577,
        "Gone Girl",
        "/ts996lKsxvjkO2yiYG0ht4qAicO.jpg",
        2014,
        "A marriage collapses into a media circus when a wife disappears on their anniversary.",
        ["Mystery", "Thriller", "Drama"],
        { runtime: 149, imdbRating: 8.1 },
      ),
      movie(
        6977,
        "No Country for Old Men",
        "/6d5XOczc226jECq0LIX0siKtgHR.jpg",
        2007,
        "A hunter, a hitman, and a sheriff collide over a satchel of cash in West Texas.",
        ["Crime", "Drama", "Thriller"],
        { runtime: 122, imdbRating: 8.2 },
      ),
    ],
  },
  {
    name: "Saudi Screens",
    description:
      "Landmark Saudi films and recent voices — from Wadjda's bicycle to Raven Song and Sijjin. Make space for these on the calendar.",
    movies: [
      movie(
        129112,
        "Wadjda",
        "/w4iCIZ1kWSOCt0yELjfUMNAToUF.jpg",
        2012,
        "A Saudi girl schemes for a green bicycle — and a little freedom — in Riyadh.",
        ["Drama", "Family"],
        { runtime: 98, imdbRating: 7.5 },
      ),
      movie(
        382750,
        "Barakah Meets Barakah",
        "/2zX6xziWLqNgMThGxYBMJue7RgV.jpg",
        2016,
        "A municipal worker and an Instagram influencer try to date in Jeddah under watchful eyes.",
        ["Comedy", "Romance"],
        { runtime: 88, imdbRating: 6.8 },
      ),
      movie(
        618214,
        "The Perfect Candidate",
        "/wxHGzOY7SiEnVt5kp5Hjj5ImpK6.jpg",
        2020,
        "A doctor runs for municipal office after a dusty road blocks her clinic — Haifaa al-Mansour's sharp satire.",
        ["Drama", "Comedy"],
        { runtime: 101, imdbRating: 6.9 },
      ),
      movie(
        287628,
        "Theeb",
        "/qixAor6q0GDPXcMEVgVi2fnWMb9.jpg",
        2014,
        "A Bedouin boy is pulled into a desert wartime trek that tests every survival instinct.",
        ["Adventure", "Drama", "Thriller"],
        { runtime: 100, imdbRating: 7.2 },
      ),
      movie(
        1042075,
        "Raven Song",
        "/mr4T2539fogjPxdIO8cXpeZlsjk.jpg",
        2022,
        "A young man from a conservative village confronts identity and desire in modern Saudi Arabia.",
        ["Drama"],
        { runtime: 95, imdbRating: 6.5 },
      ),
      movie(
        501591,
        "Born a King",
        "/hx3aLmbP9mBDaS5gQpO1fssMOC6.jpg",
        2019,
        "Young Prince Faisal's 1919 diplomatic journey to London — history with a coming-of-age pulse.",
        ["Drama", "History"],
        { runtime: 103, imdbRating: 6.4 },
      ),
      movie(
        1127087,
        "Sijjin",
        "/dnKod1VGfTR44CCvsABd8D0ifVK.jpg",
        2023,
        "Saudi horror that leans into folklore dread — a different kind of crew night.",
        ["Horror"],
        { runtime: 98, imdbRating: 6.2 },
      ),
    ],
  },
  {
    name: "Middle East & Beyond",
    description:
      "Stories from the Arab world and its neighbors — intimate, fierce, and worth arguing about after the credits.",
    movies: [
      movie(
        517814,
        "Capernaum",
        "/mFnfTVADj8yOxwzprYOmTPselk8.jpg",
        2018,
        "A Lebanese boy sues his parents for bringing him into a world that won't protect him.",
        ["Drama"],
        { runtime: 126, imdbRating: 8.4 },
      ),
      movie(
        2011,
        "Persepolis",
        "/aU8i2QAdTyRR1nYb36Gq51xXP8p.jpg",
        2007,
        "An Iranian girl comes of age through revolution and exile, drawn in stark animation.",
        ["Animation", "Drama"],
        { runtime: 95, imdbRating: 8.0 },
      ),
      movie(
        496243,
        "Parasite",
        "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
        2019,
        "A hungry family infiltrates a wealthy household — class warfare with a grin that turns.",
        ["Comedy", "Thriller", "Drama"],
        { runtime: 133, imdbRating: 8.5 },
      ),
      movie(
        494943,
        "Omar",
        "/cp5I2CzZP2p1AfxRT33hf9XHfQs.jpg",
        2013,
        "A young Palestinian is torn between love, loyalty, and the machinery of occupation.",
        ["Drama", "Thriller"],
        { runtime: 96, imdbRating: 7.1 },
      ),
      movie(
        67,
        "Paradise Now",
        "/qWZkYa8VdcDZk8uzRB2PfhpM9IL.jpg",
        2005,
        "Two friends from Nablus prepare for a mission that will change everything they know about themselves.",
        ["Drama", "Thriller", "War"],
        { runtime: 90, imdbRating: 7.0 },
      ),
      movie(
        47324,
        "Cairo Station",
        "/zm8ET6PSfPT6pozgvjR7htaZFjy.jpg",
        1958,
        "Chahine's classic of desire and class colliding on the platforms of Cairo's railway station.",
        ["Drama", "Crime"],
        { runtime: 77, imdbRating: 7.4 },
      ),
      movie(
        46707,
        "The Night of Counting the Years",
        "/vyhW3umTG8qNrK4XjlXVtvpQ79F.jpg",
        1969,
        "Egyptian masterpiece about tomb robbers, heritage, and the weight of the dead.",
        ["Drama", "History"],
        { runtime: 102, imdbRating: 7.6 },
      ),
      movie(
        517286,
        "Yomeddine",
        "/i9v06DMMNDSG4EDcE3Y7RLGo1pD.jpg",
        2018,
        "A cured leprosy patient leaves his colony to find family — a road movie with enormous heart.",
        ["Drama", "Comedy"],
        { runtime: 97, imdbRating: 7.2 },
      ),
    ],
  },
];

export function seedMovieToDoc(m: SeedMovie) {
  return {
    tmdbId: m.tmdbId,
    title: m.title,
    poster: `${TMDB}${m.posterPath}`,
    backdrop: m.backdropPath ? `${BACKDROP}${m.backdropPath}` : undefined,
    overview: m.overview,
    genres: m.genres,
    runtime: m.runtime,
    releaseYear: m.releaseYear,
    imdbRating: m.imdbRating,
  };
}
